version: "3.9"

services:
  nkdt-api:
    container_name: nkdt-api
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "6062:3000"   # chỉ Nginx dùng
    depends_on:
      - nkdt-mysql
    networks:
      - nkdt-network

  nkdt-mysql:
    container_name: nkdt-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@Nkdt2026!
      MYSQL_DATABASE: nkdt_db
      MYSQL_USER: nkdt_user
      MYSQL_PASSWORD: Nkdt@MySQL2026!
    volumes:
      - nkdt_mysql_data:/var/lib/mysql
    networks:
      - nkdt-network

networks:
  nkdt-network:
    driver: bridge

volumes:
  nkdt_mysql_data:
